# coding: utf-8

"""
    Cervinodata API documentation

    <div style='margin: 2em 0;'> <p> Before you get going with the Cervinodata API, set up Cervinodata (read the support page here: <a href='https://support.cervinodata.com/hc/en-nl/articles/360004363237' target='_blank'>How to set up the Cervinodata API</a>). </p> <h3>To use the Cervinodata API, you need all of the following:</h3> <p> <ol> <li>An active Cervinodata account, you can start a free trial <a href='https://app.cervinodata.com/register' target='_blank'>here</a></li> <li>At least one connection to a platform (check <a href='https://app.cervinodata.com/data-sources-connections' target='_blank'>here</a>)</li> <li>At least one account switched ON (check <a href='https://app.cervinodata.com/accounts' target='_blank'>here</a>)</li> <li>At least one data refresh executed (check <a href='https://app.cervinodata.com/manual-data-refresh' target='_blank'>here</a>)</li> <li>An active API token (check <a href='https://app.cervinodata.com/settings#/api' target='_blank'>here</a>)</li> </ol> </p> <p> Note that limits apply for <a href='https://support.cervinodata.com/hc/articles/360014265139' target='_blank'>Free plan users</a>. </p> <p> If you wish to automate your Cervinodata API connection, check out the list of client API's at <a href='https://github.com/Cervinodata' target='_blank'>https://github.com/Cervinodata</a>. </p> </div>  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: support@cervinodata.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest

import cervinodata_api
from cervinodata_api.api.analytics_data_product_metrics_api import AnalyticsDataProductMetricsApi  # noqa: E501
from cervinodata_api.rest import ApiException


class TestAnalyticsDataProductMetricsApi(unittest.TestCase):
    """AnalyticsDataProductMetricsApi unit test stubs"""

    def setUp(self):
        self.api = cervinodata_api.api.analytics_data_product_metrics_api.AnalyticsDataProductMetricsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_ga4_report_per_product_name_per_organisation_per_property_per_week(self):
        """Test case for get_ga4_report_per_product_name_per_organisation_per_property_per_week

        Return GA4 report per product name per organisation per property per week  # noqa: E501
        """
        pass

    def test_get_ga4_report_per_product_sku_per_organisation_per_property_per_week(self):
        """Test case for get_ga4_report_per_product_sku_per_organisation_per_property_per_week

        Return GA4 report per product sku per organisation per property per week  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
